@startuml
skinparam Style strictuml

participant GeneralInputParser <<class>>
participant EventParser <<class>>
participant OrderParser <<class>>

GeneralInputParser -> EventParser: parseInput(userInput)
activate EventParser
EventParser -> OrderParser: parseOrder(userInput, Event.keywords)
activate OrderParser
OrderParser --> EventParser : userInputs : String[]
deactivate OrderParser
note right of EventParser : userInputs[0] is the eventName\nuserInputs[1] is the eventDescription

create "x:AddEventCommand" AS AddEventCommand
EventParser -> AddEventCommand: new AddEventCommand(userInputs[0], userInputs[1])
activate AddEventCommand
AddEventCommand --> EventParser : x
deactivate AddEventCommand

EventParser --> GeneralInputParser : x
deactivate EventParser

@enduml