@startuml
skinparam Style strictuml
box Category Load Logic
participant ":Logic" as logic
participant "<<class>>\nCategory" as category
participant ":FileManager" as fileManager
participant "<<class>>\nGeneralFileParser" as generalFileParser
participant ":AddCategoryFromFileCommand" as AddCategoryFromFileCommand

activate logic

logic -> logic: loadFile(SavableType.CATEGORY)
activate logic

logic -> fileManager: openCategoryFile()
activate fileManager
fileManager -[dashed]-> logic: hasFileErrors: boolean
deactivate fileManager
    alt !hasFileErrors
    else
        logic -> fileManager : getNextLine()
        activate fileManager
        fileManager -[dashed]-> logic : hasNextLine:boolean
        deactivate fileManager
        loop hasNextLine
            logic -> fileManager : readNextLine();
            activate fileManager
            fileManager -[dashed]-> logic : line:String
            deactivate fileManager
            logic -> generalFileParser : getCommandFromFileInput(line: String)
            activate generalFileParser
            create AddCategoryFromFileCommand
            generalFileParser -> AddCategoryFromFileCommand: new AddCategoryFromFileCommand ("add", line)
            activate AddCategoryFromFileCommand
            AddCategoryFromFileCommand --> generalFileParser: command:AddCategoryFromFileCommand
            deactivate AddCategoryFromFileCommand
            generalFileParser --> logic : command:AddCategoryFromFileCommand
            deactivate generalFileParser
            logic -> AddCategoryFromFileCommand : execute(..)
            activate AddCategoryFromFileCommand
            AddCategoryFromFileCommand -> category : addCategory(line)
            activate category
            category -[dashed]-> AddCategoryFromFileCommand
            deactivate
            AddCategoryFromFileCommand -[dashed]-> logic
            deactivate AddCategoryFromFileCommand
            destroy AddCategoryFromFileCommand
            logic -> fileManager : getNextLine();
            activate fileManager
            fileManager -[dashed]-> logic : hasNextLine:boolean
            deactivate fileManager

        end
    end
    logic -[dashed]-> logic
    deactivate logic


end box
@enduml