@startuml
!include style.puml
skinparam Style strictuml
box Category Command Logic

participant ":otherClasses" as externalClasses
participant ":CategoryParser" as CategoryParser
participant ":Category" as Category



externalClasses -> CategoryParser : parseInput("Category [text]")
activate CategoryParser

alt validAddCommand || validDeleteCommand || validListCommand
    create CategoryCommand
    CategoryParser -> CategoryCommand : new CategoryCommand(...)
    activate CategoryCommand
    CategoryCommand -[dashed]-> CategoryParser: commandToExecute:CategoryCommand
    deactivate CategoryCommand
else default
    create InvalidCommand
    CategoryParser -> InvalidCommand : new InvalidCommand()
    activate InvalidCommand
    InvalidCommand -[dashed]-> CategoryParser: commandToExecute:InvalidCommand
    deactivate InvalidCommand
end
CategoryParser -[dashed]-> externalClasses : commandToExecute
deactivate CategoryParser

alt CategoryCommand
    externalClasses -> CategoryCommand : execute()
    activate CategoryCommand
    alt subcommand.equals("add")
        CategoryCommand -> Category : addCategory()
        activate Category
        Category -[dashed]-> CategoryCommand: feedback:String
        deactivate Category
    else subcommand.equals("delete")
        CategoryCommand -> Category : deleteCategory()
        activate Category
        Category -[dashed]-> CategoryCommand: feedback:String
        deactivate Category
    else subcommand.equals("list")
        CategoryCommand -> Category : listCategories()
        activate Category
        Category -[dashed]-> CategoryCommand: feedback:String
        deactivate Category
    end
    CategoryCommand -[dashed]-> externalClasses
    deactivate CategoryCommand
    destroy CategoryCommand
else InvalidCommand
    externalClasses -> InvalidCommand : execute()
    activate InvalidCommand
    InvalidCommand -> InvalidCommand : printErrorMessage()
    activate InvalidCommand
    deactivate InvalidCommand
    InvalidCommand -[dashed]-> externalClasses
    destroy InvalidCommand
end


end box
@enduml