@startuml
!include style.puml
skinparam Style strictuml
box Category Command Logic

participant ":Logic   " as logic
participant "<<class>>\nCategoryParser" as CategoryParser
participant "<<class>>\nCategory" as Category
participant ":CategoryCommand" as CategoryCommand
participant ":InvalidCommand" as InvalidCommand
participant "<<class>>\nGeneralInputParser" as generalinputparser
activate logic
logic -> generalinputparser : getCommandFromUserInput(userInput:String)
activate generalinputparser
generalinputparser -> CategoryParser : parseInput(userInput:String)
activate CategoryParser

alt validAddCommand || validDeleteCommand || validListCommand
    create CategoryCommand
    CategoryParser -> CategoryCommand : new CategoryCommand(...)
    activate CategoryCommand
    CategoryCommand -[dashed]-> CategoryParser: commandToExecute:Command
    deactivate CategoryCommand
else default
    create InvalidCommand
    CategoryParser -> InvalidCommand : new InvalidCommand()
    activate InvalidCommand
    InvalidCommand -[dashed]-> CategoryParser: commandToExecute:InvalidCommand
    deactivate InvalidCommand
end
CategoryParser -[dashed]-> generalinputparser : commandToExecute:Command
deactivate CategoryParser
generalinputparser -[dashed]-> logic : commandToExecute:Command
deactivate generalinputparser
alt CategoryCommand
    logic -> CategoryCommand : execute()
    activate CategoryCommand
    alt subcommand.equals("add")
        CategoryCommand -> Category : addCategory()
        activate Category
        Category -[dashed]-> CategoryCommand: feedback:String
        deactivate Category
    else subcommand.equals("delete")
        CategoryCommand -> Category : deleteCategory()
        activate Category
        Category -[dashed]-> CategoryCommand: feedback:String
        deactivate Category
    else subcommand.equals("list")
        CategoryCommand -> Category : listCategories()
        activate Category
        Category -[dashed]-> CategoryCommand: feedback:String
        deactivate Category
    end
    CategoryCommand -[dashed]-> logic
    deactivate CategoryCommand
    destroy CategoryCommand
else InvalidCommand
    logic -> InvalidCommand : execute()
    activate InvalidCommand
    InvalidCommand -> InvalidCommand : printErrorMessage()
    activate InvalidCommand
    deactivate InvalidCommand
    InvalidCommand -[dashed]-> logic
    destroy InvalidCommand
end
deactivate logic


end box
@enduml